import styles from "./layout.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <h1>Demo</h1>
          <nav className={styles.nav}>
            <a href="a">Contact</a>
            <a href="b">About</a>
          </nav>
        </header>
        {children}
      </body>
    </html>
  );
}
