import Link from "next/link";

import styles from "./layout.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Product page",
  description: "Generated by create next app",
};

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <nav className={styles.nav}>
        <Link href="/products/women">여성옷</Link>
        <Link href="./products/men">남성옷</Link>
      </nav>
      <section className={styles.product}>{children}</section>
    </main>
  );
}
