import Link from "next/link";

import { Metadata } from "next";
import styles from "./layout.module.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Awesome product website | Total products",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function ProductLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <nav className={styles.nav}>
        <Link href="/products/women">여성옷</Link>
        <Link href="./products/men">남성옷</Link>
      </nav>
      <section className={styles.product}>{children}</section>
    </main>
  );
}
